### PR TITLE
Changed to a more minimalistic theme

### PR DESCRIPTION
**Pull request by mrbech**
Tried to mimic Mikkels minimal look but doing as little work as possible, so this is based on https://github.com/siawyoung/immaculate with the changes:
- Our frontpage is not a blog, the blog now lives in /blog/...
- We use `Montsserat` as font (dont think this is the one Mikkel wanted but he never replied)
- Some minor style corrections and changes to the _layouts

I added the following on top of our current sites content:
- A blog, since we got that more or less for free with the theme..
- Start on the layout for wines, current idea from @cstpdk (as i understood it): we have a page per winery where all the vines we import will be presented on a single page.

What next:
- We probably want the layout on `index` and `about` to be slightly different.
- If we want to go with the winery layout we really need to figure out how to show them on the `wine` page. I was thinking about showing logos, but that is probably a bit too dull...

### CODE REVIEW

**Comment by cstpdk** [comment]
Very bauhaus

lør. 25. maj 2019 13.31 skrev Martin Bech <notifications@github.com>:

**Comment by mrbech** [comment]
Also the copy paste from facebook blogpost is just a placeholder :P

**Comment by cstpdk** [comment]
Like the look. Am I understanding correctly that we want to just have the "winery" pages be "hardcoded", i.e. the wines themselves are not an entity?

**Comment by mrbech** [comment]
There is no "we" ;) I actually thought that was what you had been doing :) We can totally have the wines as separate entities, (we must go deeper!). Perhaps just "load" them into winery pages? Right now we dont have alot of wines so separate wines page might be a bit overkill

**Comment by cstpdk** [comment]
Yeah, I wasn't thinking separate page for each wine, just keeping wine as a data entity (can't remember the jekyll word, a `_wine` thingy), but still just loop them on the winery page

**Comment by mrbech** [comment]
Sounds cool to me, should you or I make the change? :)

**Comment by sofusalbertsen** [comment]
I think this is a go, much more slick than the other layout (even though I liked the other).
Shouldn't we just hit "go" on this version, and take it from there?

**Review by sofusalbertsen — APPROVED** [review]
My name is @sofusalbertsen  and I approve this PR :+1:

**Comment by mrbech** [comment]
Agreed, ill merge and we can take it from here :+1:

**Pull request merged**
